In [181]:
import numpy as np
import math

Gerador e transformador
Base de potencia = 100 MVA

In [145]:
Sb=100000000.0

#Gerador
Vg= 138000.0 #V phase-phase
Sg=250000000.0 #VA
Xg=0.08 #% na base de 250 MVA
#Em pu
Xg_pu=Xg*Sg/Sb
Sg_pu=Sg/Sb

#Transformador
St=300000000.0 #VA
Xt=0.1 #% na base de 100 MVA
#Em PU
St_pu=St/Sb

Linha de transmissão

In [149]:
l=120 #distancia em km
z1=(0.353803 + 0.524941j)*l
y1 = (complex(3*10**-8,3.13194*(10**-6)))*l

#Em pu
zb=Vg**2/Sb
yb=1/zb
z1_pu=z1/zb
y1_pu=y1/yb

Carga

In [221]:
Fp= [-0.92,0.92] #negativo = indutivo ;positivo = capacitivo
Pc=40000000
Vc= [.95,1.05]


Matrizes e calculo

In [235]:
def calcular(V_pu,P,fp_pu): 
    S=Pc*math.cos(fp_pu)
    S_pu= S/Sb
    I_pu=complex(S_pu/V_pu*math.cos(fp_pu),S_pu/V_pu*math.sin(fp_pu))

    
    Carg = np.array([[V_pu],[I_pu]])
    
    Impedancia_Gera = np.array([[1,Xg_pu],
                       [0,1]])
    
    Impedancia_Transfo = np.array([[1,Xt],
                       [0,1]])
    
    Impedancia_Linha =   np.array([[1+(z1_pu*y1)/2     ,z1_pu],
                               [y1_pu*(1+(z1_pu*y1_pu)/4),1+(z1_pu*y1_pu)/2]])
    
    Impedancia_Total = Impedancia_Gera @ Impedancia_Transfo @ Impedancia_Linha
    
    Font = Impedancia_Total@Carg
    print("V em pu valor absoluto na fonte:")
    print(abs(Font[0]))
    print("A em pu valor absoluto na fonte:")
    print(abs(Font[1]))

In [236]:
for i in Vc:
    for j in Fp:
        print("Utilizadno o valor de V na carga = "+str(i)+" e fator de potencia = "+str(j))
        calcular(i,Pc,j)
        print("")

Utilizadno o valor de V na carga = 0.95 e fator de potencia = -0.92
V em pu valor absoluto na fonte:
[1.09845503]
A em pu valor absoluto na fonte:
[0.20319668]

Utilizadno o valor de V na carga = 0.95 e fator de potencia = 0.92
V em pu valor absoluto na fonte:
[0.97887436]
A em pu valor absoluto na fonte:
[0.30905536]

Utilizadno o valor de V na carga = 1.05 e fator de potencia = -0.92
V em pu valor absoluto na fonte:
[1.1841547]
A em pu valor absoluto na fonte:
[0.17542308]

Utilizadno o valor de V na carga = 1.05 e fator de potencia = 0.92
V em pu valor absoluto na fonte:
[1.07415732]
A em pu valor absoluto na fonte:
[0.29154687]



# Questao 2

In [240]:
Vc= [.95,1.05]
Vc=np.array([Vc[1],complex(Vc[1]*math.cos(-2.09),Vc[1]*math.sin(-2.09)),complex(Vc[1]*math.cos(2.09),Vc[1]*math.sin(2.09))])
Vc

array([ 1.05      +0.j        , -0.52099836-0.91162531j,
       -0.52099836+0.91162531j])

In [241]:
Ic=0.4
Ic=np.array([Ic,complex(Ic*math.cos(-2.09),Ic*math.sin(-2.09)),complex(Ic*math.cos(2.09),Ic*math.sin(2.09))])
Ic

array([ 0.4       +0.j        , -0.19847557-0.34728583j,
       -0.19847557+0.34728583j])

In [253]:
Z=np.array([[0.412396 + 0.98981j, 0.0585923 + 0.464869j, 0.0585923 + 0.464869j],
[0.0585923 + 0.464869j, 0.412396 + 0.98981j, 0.0585923 + 0.464869j],
[0.0585923 + 0.464869j, 0.0585923 + 0.464869j, 0.412396 + 0.98981j]])*l

Y=np.array([[3*10**-8 + 1j*2.70829*10**-6, 1j*-4.2365*10**-7 ,1j*-4.2365*10**7],
[1j*-4.2365*10**-7, 3*10**-8 + 1j*2.70829*10**-7, 1j*-4.2365*10**7],
[1j*-4.2365*10**-7, 1j*-4.2365*10**-7, 3*10**-7 + 1j*2.70829*10**6] ])*l

In [267]:
R=np.array([[0, 1, 0],
           [0, 0, 1],
           [1, 0, 0]])
#1/6
z1=(Z/6)[0][0]-(Z/6)[1][0]
y1=(Y/6)[0][0]-(Y/6)[1][0]
#1/3
z2=((Z/3)@R)[0][0]-((Z/3)@R)[1][0]
y2=((Y/3)@R)[0][0]-((Y/3)@R)[1][0]
#1/3
z3=((Z/3)@R@R)[0][0]-((Z/3)@R@R)[1][0]
y3=((Y/3)@R@R)[0][0]-((Y/3)@R@R)[1][0]
#1/6
z4=((Z/6)@R@R@R)[0][0]-((Z/6)@R@R@R)[1][0]
y4=((Y/6)@R@R@R)[0][0]-((Y/6)@R@R@R)[1][0]

In [274]:
Z

array([[49.48752 +118.7772j ,  7.031076 +55.78428j,  7.031076 +55.78428j],
       [ 7.031076 +55.78428j, 49.48752 +118.7772j ,  7.031076 +55.78428j],
       [ 7.031076 +55.78428j,  7.031076 +55.78428j, 49.48752 +118.7772j ]])

(7.076073999999998+10.49882j)

(-14.152147999999997-20.99764j)

(7.076073999999998+10.49882j)